#!/bin/bash

# whi daemon
# chkconfig: 345 20 80
# description: whi daemon
# processname: whi

export USER=root
export PATH=/opt/node/bin:$PATH
export NODE_ENV=production
export NODE_PATH=/opt/node/lib/node_modules:$NODE_PATH
export DEBUG="whi:*"

WHI_ROOT=/opt/whi
SCRIPT=$WHI_ROOT/server.js
DAEMON=${WHI_ROOT}/node_modules/.bin/forever
DAEMONO_PTS=""

NAME=whi-server
DESC="wiredcraft http checker server"
LOGFILE=/var/log/$NAME.log
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

do_install() {
    printf "%-50s" "Installing dependencies ..."
    cd ${WHI_REPO}
    npm install debug forever express redis cradle request > /dev/null
}

do_start() {
    bash -c "$DAEMON start \
        --append \
        --pidFile $PIDFILE \
        --logFile $LOGFILE \
        $SCRIPT" - $USER
}

do_stop() {
    bash -c "$DAEMON stop $SCRIPT" - $USER
}

case "$1" in
start)
    printf "%-50s" "Starting $DESC ..."
    do_install
    do_start
;;
stop)
    printf "%-50s" "Stopping $DESC ..."
    do_stop
;;
reload)
    printf "%-50s" "Reloading $DESC ..."
    do_stop
    do_start
;;
restart)
    printf "%-50s" "Restarting $DESC ..."
    do_stop
    do_start
;;

*)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac
